name: Test

on:
  push:
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        # https://nodejs.org/en/about/releases/
        node:
          - '20'
          - '20.12.2'
          - '22'
          - '24'
      fail-fast: false

    name: Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          # Enable this when setup-node v5 is released, and release is broken
          # package-manager-cache: false
      - name: Install Dependency
        run: npm ci
      - name: Build
        run: npm run build
      - name: Install pnpm  # For publint
        run: npm install -g pnpm
      - name: publint
        run: npx publint

  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Run pinact
        uses: suzuki-shunsuke/pinact-action@49cbd6acd0dbab6a6be2585d1dbdaa43b4410133 # v1.0.0
        with:
          skip_push: "true"
